#version: ${full.version}
#############################################################
# +-------------------------------------------------------+ #
# |                  EssentialsX Discord                  | #
# +-------------------------------------------------------+ #
#############################################################

# This config file only works when the EssentialsXDiscord jar is installed.

# You need to create a bot user in order to connect your server to Discord.
# You can find instructions on this here: #TODO write up docs

# The token for your bot from the Discord Developers site.
token: "INSERT-TOKEN-HERE"

# The ID of your server.
guild: 0

# The channels that will be used for messaging, defaulting to the primary channel.
channels:
  primary:
    id: 0

# Determine which channels certain messages will go to.
messages:
  chat: primary

# Status message for the bot to display. The activity must be playing or listening.
status:
  activity: "playing"
  message: "Minecraft"
