name: EssentialsDiscord
main: net.essentialsx.discord.EssentialsDiscord
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://essentialsx.net/
description: Provides integration between Minecraft and Discord servers.
authors: [mdcfe, JRoy, pop4959, Glare]
depend: [Essentials]
softdepend: [EssentialsChat, PlaceholderAPI]
api-version: 1.13
commands:
  discordbroadcast:
    description: Broadcasts a message to the specified Discord channel.
    usage: /<command> <channel> <msg>
    aliases: [dbroadcast, dbc, dbcast, ediscordbroadcast, edbroadcast, edbc, edbcast]
  discord:
    description: Sends the discord invite link to the player.
    usage: /<command>
    aliases: [ediscord]
permissions:
  essentials.discord.markdown:
    description: Allows the bearer to bypass the Discord markdown filter
  essentials.discord.ping:
    description: Allows the bearer to ping users in Discord
  essentials.discord.receive.<channel>:
    description: Allows the bearer to receive messages from the specified channel
  essentials.discord:
    description: Allows access to the /discord command
  essentials.discordbroadcast:
    description: Allows access to the /discordbroadcast command
  essentials.discordbroadcast.markdown:
    description: Allows the bearer to bypass the Discord markdown filter for /discordbroadcast
  essentials.discordbroadcast.ping:
    description: Allows the bearer to ping users in Discord for /discordbroadcast
  essentials.discordbroadcast.<channel>:
    description: Allows access to the /discordbroadcast command for the specified channel
