name: EssentialsDiscord
main: net.essentialsx.discord.EssentialsDiscord
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://essentialsx.net/
description: Provides integration between Minecraft and Discord servers.
authors: [mdcfe, JRoy, pop4959, Glare]
depend: [Essentials]
softdepend: [EssentialsChat, PlaceholderAPI]
api-version: 1.13
folia-supported: true
commands:
  discordbroadcast:
    description: Broadcasts a message to the specified Discord channel.
    usage: /<command> <channel> <msg>
    aliases: [dbroadcast, dbc, dbcast, ediscordbroadcast, edbroadcast, edbc, edbcast]
  discord:
    description: Sends the discord invite link to the player.
    usage: /<command>
    aliases: [ediscord]