# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials
main: com.earth2me.essentials.Essentials
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: TeamCity
website: http://www.earth2me.net:8001/
description: Provides an essential, core set of commands for Bukkit.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology]
softdepend: [Permissions]
commands:
  afk:
    description: Marks you as away-from-keyboard.
    usage: /<command>
    aliases: [eafk]
  antioch:
    description: 'A little surprise for operators. Warning: Point away from face.'
    usage: /<command>
    aliases: [eantioch]
  back:
    description: Teleports you to your location prior to teleporting/spawning/warping.
    usage: /<command>
    aliases: [eback]
  backup:
    description: Runs the backup command
    usage: /<command>
    aliases: [ebackup]
  balance:
    description: States the current balance of a player.  Defaults to self.
    usage: /<command> <player>
    aliases: [bal,emoney,ebalance,ebal]
  ban:
    description: Bans a player.
    usage: /<command> [player] <reason>
    aliases: [eban]
  banip:
    description: Bans an IP address.
    usage: /<command> [address]
    aliases: [ebanip]
  broadcast:
    description: Broadcasts a message to the entire server.
    usage: /<command> [msg]
    aliases: [ebroadcast,bcast]
  bigtree:
    description: Spawn a big tree where you are looking.
    usage: /<command> [tree|redwood]
    aliases: [ebigtree]
  burn:
    description: Set a player on fire.
    usage: /<command> [player] [seconds]
    aliases: [eburn]
  clearinventory:
    description: Clear all items in your inventory.
    usage: /<command>
    aliases: [ci,eci,eclearinventory]
  compass:
    description: Describes your current bearing.
    usage: /<command>
  deljail:
    description: Removes a jail
    usage: /<command> [jailname]
  delwarp:
    description: Deletes the specified warp.
    usage: /<command> [warp]
    aliases: [edelwarp,remwarp,rmwarp]
  depth:
    description: States current depth, relative to sea level.
    usage: /depth
    aliases: [edepth]
  eco:
    description: Manages the server economy.
    usage: /<command> [give|take|reset] [player] [amount]
    aliases: economy
  essentials:
    description: Reloads essentials.
    usage: /<command>
  ext:
    description: Extinguish players.
    usage: /<command> <player>
    aliases: [extinguish]
  getpos:
    description: Get your current coordinates.
    usage: /<command>
    aliases: [coords,egetpos]
  gc:
    description: Reports garbage collection info; useful to plugin/CraftBukkit developers
    usage: /<command>
    aliases: [mem,memory,egc]
  give:
    description: Give a player an item.
    usage: /<command> [player] [item|numeric] <amount>
    aliases: [egive]
  god:
    description: Enables your godly powers.
    usage: /<command>
    aliases: [tgm,godmode,egod]
  heal:
    description: Heals you or the given player.
    usage: /<command> <player>
    aliases: [eheal]
  help:
    description: Views a list of available commands.
    usage: /<command>
    aliases: [ehelp]
  helpop:
    description: Request help from online operators.
    usage: /<command> [message]
  home:
    description: Teleport to your home.
    usage: /<command> <player>
    aliases: [ehome]
  info:
    description: Shows information set by the server owner
    usage: /<command> [chapter] [page]
    aliases: [ifo,einfo,eabout]
  invsee:
    description: See the inventory of other players.
    usage: /<command> <player>
    aliases: [einvsee]
  item:
    description: Spawn an item.
    usage: /<command> [item|numeric] <amount>
    aliases: [i,eitem]
  jails:
    description: List all jails.
    usage: /<command>
    aliases: [ejails]
  jump:
    description: Jumps to the nearest block in the line of sight.
    usage: /<command>
    aliases: [j,ejump]
  kick:
    description: Kicks a specified player with a reason.
    usage: /<command> <player> <reason>
    aliases: [ekick]
  kickall:
    description: Kicks all players off the server except the issuer.
    usage: /<command> <reason>
  kit:
    description: Obtains the specified kit or views all available kits.
    usage: /<command> <kit>
  kill:
    description: Kills specified player.
    usage: /<command> <player>
  list:
    description: List all online players.
    usage: /<command>
    aliases: [playerlist,who,online,elist]
  lightning:
    description: Command the power of Thor. Look and strike or pass a player args.
    usage: /<command> <player>
  mail:
    description: Manages inter-player, intra-server mail.
    usage: /<command> [read|clear|send [to] [message]]
    aliases: [email]
  me:
    description: Describes an action in the context of the player.
    usage: /<command> [description]
    aliases: [eme]
  motd:
    description: Views the Message Of The Day.
    usage: /<command>
    aliases: [emotd]
  msg:
    description: Sends a private message to the specified player.
    usage: /<command> <to> <message>
    aliases: [m,t,emsg]
  mute:
    description: Mutes or unmutes a player.
    usage: /<command> [player] <datediff>
    aliases: [emute]
  nick:
    description: Change your nickname or that of another player.
    usage: /<command> <player> [nickname|off]
    aliases: [enick]
  pay:
    description: Pays another player from your balance
    usage: /<command> [player] [amount]
    aliases: [epay]
  ping:
    description: Pong!
    usage: /<command>
    aliases: [pong,eping]
  plugin:
    description: Enables, disables, or reloads a plugin.
    usage: /<command> [enable|disable|reload] [plugin]
    aliases: [plugins,eplugin]
  powertool:
    description: Assigns a command to the item in hand, {player} will be replaced by the name of the player that you click.
    usage: /<command> [command] <arguments>
    aliases: [pt,epowertool,ept]
  r:
    description: Quickly reply to the last player to message you.
    usage: /<command> [message]
    aliases: [er]
  realname:
    description: Displays the username of a user based on his/her nickname.
    usage: /<command> [nickname]
    aliases: [erealname]
  reloadall:
    description: Reloads all plugins.
    usage: /<command>
    aliases: [rel,ereloadall,ereload,erel]
  rules:
    description: Views the server rules.
    usage: /<command>
    aliases: [erules]
  seen:
    description: Shows the last logout time of a player
    usage: /<command> [playername]
  sell:
    description: Sells the item currently in your hand.
    usage: /<command> [itemname|id|hand|inventory|blocks] [-][amount]
    aliases: [esell]
  sethome:
    description: Set your home to your current location.
    usage: /<command>
    aliases: [esethome]
  setjail:
    description: Creates a jail where you specified named [jailname]
    usage: /<command> [jailname]
    aliases: [esetjail]
  setwarp:
    description: Creates a new warp.
    usage: /<command> [warp]
    aliases: [createwarp,esetwarp]
  setworth:
    description: Set the value of an item for sale, will add item if doesn't exist
    usage: /<command> [itemname|id] [price]
    aliases: [esetworth]
  socialspy:
    description: Toggles if you can see /msg and /mail commands in chat.
    usage: /<command> 
  spawnmob:
    description: Spawns a mob.
    usage: /<command> [mob]<:data><,mount<:data>> <amount>
    aliases: [espawnmob]
  suicide:
    description: Causes you to perish.
    usage: /<command>
    aliases: [esuicide]
  tempban:
    description: Temporary ban a user.
    usage: /<command> [playername] [datediff]
  thunder:
    description: Enable/disable thunder.
    usage: /<command> <true/false> [duration]
  time:
    description: Change the server time to day or night.
    usage: /<command> [day|night]
    aliases: [etime]
  togglejail:
    description: Prevents a player from interacting with the world and teleports him/her to the the jail specified
    usage: /<command> [player] [jailname] <datediff>
    aliases: [tjail,etogglejail]
  top:
    description: Teleport to the highest block at your current coordinates.
    usage: /<command>
    aliases: [etop]
  tp:
    description: Teleport to a player.
    usage: /<command> [player]
    aliases: [etp]
  tpa:
    description: Request to teleport to the specified player.
    usage: /<command> <player>
  tpaccept:
    description: Accepts a teleport request.
    usage: /<command>
  tpahere:
    description: Request that the specified player teleport to you.
    usage: /<command> <player>
  tpall:
    desctiption: Teleport all online players to another player.
    usage: /<command> <player>
  tpdeny:
    description: Reject a teleport request.
    usage: /<command>
  tphere:
    description: Teleport a player to you.
    usage: /<command> [player]
    aliases: s
  tpo:
    description: Teleport override for tptoggle.
    usage: /<command> <player>
  tpohere:
    description: Teleport here override for tptoggle.
    usage: /<command> <player>
  tppos:
    description: Teleport to coordinates.
    usage: /<command> <x> <y> <z>
  tptoggle:
    description: Blocks all forms of teleportation.
    usage: /<command>
  tree:
    description: Spawn a tree where you are looking.
    usage: /<command> [tree|birch|redwood]
    aliases: [etree]
  unban:
    description: Unbans the specified player.
    usage: /<command> [player]
    aliases: pardon
    aliases: [eunban]
  unbanip:
    description: Unbans the specified IP address.
    usage: /<command> [address]
    aliases: [eunbanip,pardonip]
  unlimited:
    description: Allows the unlimited placing of items.
    usage: /<command> [list|item] <player>
    aliases: [eunlimited]
  warp:
    description: List all warps or warp to the specified location.
    usage: /<command> <warp> <player>
    aliases: [ewarp]
  weather:
    description: Setting the weather.
    usage: /<command> <storm/sun> [duration]
    aliases: [sky]
  whois:
    description: Determine the username behind a nickname.
    usage: /<command> [nickname]
    aliases: [ewhois]
  world:
    description: Switch between worlds.
    usage: /<command> [world]
    aliases: [eworld]
  worth:
    description: Calculates the worth of items in hand or as specified.
    usage: /<command> <item> <amount>
    aliases: [eworth]