# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials
main: com.earth2me.essentials.Essentials
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${project.version}-b${BUILD_NUMBER}
website: http://tiny.cc/EssentialsCommands
description: Provides an essential, core set of commands for Bukkit.
softdepend: [Vault]
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs]
commands:
  afk:
    description: Marks you as away-from-keyboard.
    usage: /<command> [player]
    aliases: [away]
  antioch:
    description: 'A little surprise for operators.'
    usage: /<command> [message]
    aliases: [grenade,tnt]
  back:
    description: Teleports you to your location prior to tp/spawn/warp.
    usage: /<command>
    aliases: [return]
  backup:
    description: Runs the backup if configured.
    usage: /<command>
  balance:
    description: States the current balance of a player.
    usage: /<command> [player]
    aliases: [bal, money]
  balancetop:
    description: Gets the top balance values.
    usage: /<command> <page>
    aliases: [baltop]
  ban:
    description: Bans a player.
    usage: /<command> <player> [reason]
  banip:
    description: Bans an IP address.
    usage: /<command> <address>
  book:
    description: Allows reopening and editing of sealed books.
    usage: /<command> [title|author [name]]
  break:
    description: Breaks the block you are looking at.
    usage: /<command>
  broadcast:
    description: Broadcasts a message to the entire server.
    usage: /<command> <msg>
    aliases: [bc, bcast, shout]
  broadcastworld:
    description: Broadcasts a message to a world.
    usage: /<command> <world> <msg>
    aliases: [bcw, bcastw, shoutworld]
  bigtree:
    description: Spawn a big tree where you are looking.
    usage: /<command> <tree|redwood|jungle>
    aliases: [largetree]
  burn:
    description: Set a player on fire.
    usage: /<command> <player> <seconds>
  clearinventory:
    description: Clear all items in your inventory.
    usage: /<command> [player|*] [item[:<data>]|*|**] [amount]
    aliases: [ci, clear, clearinvent]
  condense:
    description: Condenses items into a more compact blocks.
    usage: /<command> [<itemname>|<id>|hand|inventory]
    aliases: [compact, blocks, toblocks]
  compass:
    description: Describes your current bearing.
    usage: /<command>
    aliases: [direction]
  createkit:
    description: Create a kit in game!
    usage: /<command> <kitname> <delay>
    aliases: [kitcreate,createk,kc,ck]
  customtext:
    description: Allows you to create custom text commands.
    usage: /<alias> - Define in bukkit.yml
  delhome:
    description: Removes a home.
    usage: /<command> [player:]<name>
    aliases: [remhome, rmhome]
  deljail:
    description: Removes a jail.
    usage: /<command> <jailname>
    aliases: [remjail, rmjail]
  delwarp:
    description: Deletes the specified warp.
    usage: /<command> <warp>
    aliases: [remwarp, rmwarp,]
  depth:
    description: States current depth, relative to sea level.
    usage: /depth
    aliases: [height]
  eco:
    description: Manages the server economy.
    usage: /<command> <give|take|set|reset> <player> <amount>
    aliases: [eeco, economy]
  enchant:
    description: Enchants the item the user is holding.
    usage: /<command> <enchantmentname> [level]
    aliases: [enchantment]
  enderchest:
    description: Lets you see inside an enderchest.
    usage: /<command> [player]
    aliases: [echest, endersee, ec]
  essentials:
    description: Reloads essentials.
    usage: /<command>
    aliases: [ess, essversion]
  exp:
    description: Give, set or look at a players exp.
    usage: /<command> [show|set|give] [playername [amount]]
    aliases: [xp]
  ext:
    description: Extinguish players.
    usage: /<command> [player]
    aliases: [extinguish]
  feed:
    description: Satisfy the hunger.
    usage: /<command> [player]
    aliases: [eat]
  fly:
    description: Take off, and soar!
    usage: /<command> [player] [on|off]
  fireball:
    description: Throw a fireball.
    usage: /<command> [small|skull]
    aliases: [fireentity, fireskull]
  firework:
    description: Allows you to modify a stack of fireworks.
    usage: /<command> <<meta param>|power [amount]|clear|fire [amount]>
  gamemode:
    description: Change player gamemode.
    usage: /<command> <survival|creative|adventure|spectator> [player]
    aliases: [adventure, adventuremode, creative, creativemode, gm, gma, gmc, gms, gmt, survival, survivalmode, gmsp, sp, spec, spectator]
  gc:
    description: Reports memory, uptime and tick info.
    usage: /<command> [all]
    aliases: [lag, mem, memory, uptime, tps, entities]
  getpos:
    description: Get your current coordinates or those of a player.
    usage: /<command> [player]
    aliases: [coords, position, whereami, getlocation, getloc]
  give:
    description: Give a player an item.
    usage: /<command> <player> <item|numeric> [amount [itemmeta...]]
  god:
    description: Enables your godly powers.
    usage: /<command> [player] [on|off]
    aliases: [godmode, tgm]
  hat:
    description: Get some cool new headgear.
    usage: /<command> [remove]
    aliases: [head]
  heal:
    description: Heals you or the given player.
    usage: /<command> [player]
  help:
    description: Views a list of available commands.
    usage: /<command> [search term] [page]
  helpop:
    description: Message online admins.
    usage: /<command> <message>
    aliases: [ac, amsg]
  home:
    description: Teleport to your home.
    usage: /<command> [player:][name]
    aliases: [homes]
  ignore:
    description: Ignore or unignore other players.
    usage: /<command> <player>
    aliases: [unignore, delignore, remignore, rmignore]
  info:
    description: Shows information set by the server owner.
    usage: /<command> [chapter] [page]
    aliases: [about, ifo, inform, news]
  invsee:
    description: See the inventory of other players.
    usage: /<command> <player>
  item:
    description: Spawn an item.
    usage: /<command> <item|numeric> [amount [itemmeta...]]
    aliases: [i]
  itemdb:
    description: Searches for an item.
    usage: /<command> <item>
    aliases: [dura, durability, ei, itemno]
  jails:
    description: List all jails.
    usage: /<command>
  jump:
    description: Jumps to the nearest block in the line of sight.
    usage: /<command>
    aliases: [j, jumpto]
  kick:
    description: Kicks a specified player with a reason.
    usage: /<command> <player> [reason]
  kickall:
    description: Kicks all players off the server except the issuer.
    usage: /<command> [reason]
  kill:
    description: Kills specified player.
    usage: /<command> <player>
  kit:
    description: Obtains the specified kit or views all available kits.
    usage: /<command> [kit] [player]
    aliases: [kits, ekit]
  kittycannon:
    description: Throw an exploding kitten at your opponent.
    usage: /<command>
  lightning:
    description: The power of Thor. Strike at cursor or player.
    usage: /<command> [player] [power]
    aliases: [shock, smite, strike, thor]
  list:
    description: List all online players.
    usage: /<command> [group]
    aliases: [elist,online,eonline,playerlist,eplayerlist,plist,eplist,who,ewho]
  mail:
    description: Manages inter-player, intra-server mail.
    usage: /<command> [read|clear|send [to] [message]|sendall [message]]
    aliases: [email,eemail,memo,ememo]
  me:
    description: Describes an action in the context of the player.
    usage: /<command> <description>
    aliases: [action,eaction,describe,edescribe,eme]
  more:
    description: Fills the item stack in hand to maximum size.
    usage: /<command>
  motd:
    description: Views the Message Of The Day.
    usage: /<command> [chapter] [page]
  msg:
    description: Sends a private message to the specified player.
    usage: /<command> <to> <message>
    aliases: [w, m, t, pm, tell, whisper]
  msgtoggle:
    description: Blocks receiving all private messages.
    usage: /<command> [player] [on|off]
    aliases: [emsgtoggle]
  mute:
    description: Mutes or unmutes a player.
    usage: /<command> <player> [datediff]
    aliases: [silence]
  near:
    description: Lists the players near by or around a player.
    usage: /<command> [playername] [radius]
    aliases: [nearby]
  nick:
    description: Change your nickname or that of another player.
    usage: /<command> [player] <nickname|off>
    aliases: [enick,nickname]
  nuke:
    description: May death rain upon them.
    usage: /<command> [player]
    aliases: [enuke]
  pay:
    description: Pays another player from your balance.
    usage: /<command> <player> <amount>
    aliases: [epay]
  ping:
    description: Pong!
    usage: /<command>
    aliases: [echo, eping, pong]
  potion:
    description: Adds custom potion effects to a potion.
    usage: /<command> <clear|apply|effect:<effect> power:<power> duration:<duration>>
    aliases: [epotion,elixer]
  powertool:
    description: Assigns a command to the item in hand.
    usage: /<command> [l:|a:|r:|c:|d:][command] [arguments] - {player} can be replaced by name of a clicked player.
    aliases: [epowertool,pt]
  powertooltoggle:
    description: Enables or disables all current powertools.
    usage: /<command>
    aliases: [epowertooltoggle, ptt, pttoggle]
  ptime:
    description: Adjust player's client time. Add @ prefix to fix.
    usage: /<command> [list|reset|day|night|dawn|17:30|4pm|4000ticks] [player|*]
    aliases: [playertime]
  pweather:
    description: Adjust a player's weather
    usage: /<command> [list|reset|storm|sun|clear] [player|*]
    aliases: [playerweather, epweather]
  r:
    description: Quickly reply to the last player to message you.
    usage: /<command> <message>
    aliases: [er, reply]
  realname:
    description: Displays the username of a user based on nick.
    usage: /<command> <nickname>
    aliases: [erealname]
  recipe:
    description: Displays how to craft items.
    usage: /<command> <item> [number]
    aliases: [formula, method, erecipe, recipes]
  remove:
    description: Removes entities in your world.
    usage: /<command> <all|tamed|named|drops|arrows|boats|minecarts|xp|paintings|itemframes|endercrystals|monsters|animals|ambient|mobs|[mobType]> [radius|world]
    aliases: [eremove,butcher,ebutcher,killall,ekillall,mobkill,emobkill]
  repair:
    description: Repairs the durability of one or all items.
    usage: /<command> [hand|all]
    aliases: [fix,efix,erepair]
  rules:
    description: Views the server rules.
    usage: /<command> [chapter] [page]
    aliases: [erules]
  seen:
    description: Shows the last logout time of a player.
    usage: /<command> <playername>
    aliases: [eseen]
  sell:
    description: Sells the item currently in your hand.
    usage: /<command> <<itemname>|<id>|hand|inventory|blocks> [-][amount]
    aliases: [esell]
  sethome:
    description: Set your home to your current location.
    usage: /<command> [[player:]name]
    aliases: [esethome,createhome,ecreatehome]
  setjail:
    description: Creates a jail where you specified named [jailname].
    usage: /<command> <jailname>
    aliases: [esetjail,createjail,ecreatejail]
  setwarp:
    description: Creates a new warp.
    usage: /<command> <warp>
    aliases: [createwarp,ecreatewarp,esetwarp]
  setworth:
    description: Set the sell value of an item.
    usage: /<command> [itemname|id] <price>
    aliases: [esetworth]
  showkit:
    description: Show contents of a kit.
    usage: /<command> <kitname>
    aliases: [kitpreview,preview,kitshow]
  skull:
    description: Set the owner of a player skull
    usage: /<command> [owner]
    aliases: [eskull, playerskull, eplayerskull, head, ehead]
  socialspy:
    description: Toggles if you can see msg/mail commands in chat.
    usage: /<command> [player] [on|off]
    aliases: [esocialspy]
  spawner:
    description: Change the mob type of a spawner.
    usage: /<command> <mob> [delay]
    aliases: [changems,echangems,espawner,mobspawner,emobspawner]
  spawnmob:
    description: Spawns a mob.
    usage: /<command> <mob>[:data][,<mount>[:data]] [amount] [player]
    aliases: [mob,emob,spawnentity,espawnentity,espawnmob]
  speed:
    description: Change your speed limits.
    usage: /<command> [type] <speed> [player]
    aliases: [flyspeed,eflyspeed,fspeed,efspeed,espeed,walkspeed,ewalkspeed,wspeed,ewspeed]
  sudo:
    description: Make another user perform a command.
    usage: /<command> <player> <command [args]>
    aliases: [esudo]
  suicide:
    description: Causes you to perish.
    usage: /<command>
    aliases: [esuicide]
  tempban:
    description: Temporary ban a user.
    usage: /<command> <playername> <datediff> <reason>
    aliases: [etempban]
  thunder:
    description: Enable/disable thunder.
    usage: /<command> <true/false> [duration]
    aliases: [ethunder]
  time:
    description: Display/Change the world time. Defaults to current world.
    usage: /<command> [day|night|dawn|17:30|4pm|4000ticks] [worldname|all]
    aliases: [day,eday,night,enight,etime]
  togglejail:
    description: Jails/Unjails a player, TPs them to the jail specified.
    usage: /<command> <player> <jailname> [datediff]
    aliases: [jail,ejail,tjail,etjail,etogglejail,unjail,eunjail]
  top:
    description: Teleport to the highest block at your current position.
    usage: /<command>
    aliases: [etop]
  tp:
    description: Teleport to a player.
    usage: /<command> <player> [otherplayer]
    aliases: [tele,etele,teleport,eteleport,etp,tp2p,etp2p]
  tpa:
    description: Request to teleport to the specified player.
    usage: /<command> <player>
    aliases: [call,ecall,etpa,tpask,etpask]
  tpaall:
    description: Requests all players online to teleport to you.
    usage: /<command> <player>
    aliases: [etpaall]
  tpaccept:
    description: Accepts a teleport request.
    usage: /<command> [otherplayer]
    aliases: [etpaccept,tpyes,etpyes]
  tpahere:
    description: Request that the specified player teleport to you.
    usage: /<command> <player>
    aliases: [etpahere]
  tpall:
    description: Teleport all online players to another player.
    usage: /<command> <player>
    aliases: [etpall]
  tpdeny:
    description: Reject a teleport request.
    usage: /<command>
    aliases: [etpdeny,tpno,etpno]
  tphere:
    description: Teleport a player to you.
    usage: /<command> <player>
    aliases: [s,etphere]
  tpo:
    description: Teleport override for tptoggle.
    usage: /<command> <player> [otherplayer]
    aliases: [etpo]
  tpohere:
    description: Teleport here override for tptoggle.
    usage: /<command> <player>
    aliases: [etpohere]
  tppos:
    description: Teleport to coordinates.
    usage: /<command> <x> <y> <z> [yaw] [pitch]
    aliases: [etppos]
  tptoggle:
    description: Blocks all forms of teleportation.
    usage: /<command> [player] [on|off]
    aliases: [etptoggle]
  tree:
    description: Spawn a tree where you are looking.
    usage: /<command> <tree|birch|redwood|redmushroom|brownmushroom|jungle|junglebush|swamp>
    aliases: [etree]
  unban:
    description: Unbans the specified player.
    usage: /<command> <player>
    aliases: [pardon,eunban,epardon]
  unbanip:
    description: Unbans the specified IP address.
    usage: /<command> <address>
    aliases: [eunbanip,pardonip,epardonip]
  unlimited:
    description: Allows the unlimited placing of items.
    usage: /<command> <list|item|clear> [player]
    aliases: [eunlimited,ul,unl,eul,eunl]
  vanish:
    description: Hide yourself from other players.
    usage: /<command> [player] [on|off]
    aliases: [v,ev,evanish]
  warp:
    description: List all warps or warp to the specified location.
    usage: /<command> <pagenumber|warp> [player]
    aliases: [ewarp,warps,ewarps]
  weather:
    description: Sets the weather.
    usage: /<command> <storm/sun> [duration]
    aliases: [rain,erain,sky,esky,storm,estorm,sun,esun,eweather]
  whois:
    description: Determine the username behind a nickname.
    usage: /<command> <nickname>
    aliases: [ewhois]
  workbench:
    description: Opens up a workbench.
    usage: /<command>
    aliases: [craft,ecraft,wb,ewb,wbench,ewbench,eworkbench]
  world:
    description: Switch between worlds.
    usage: /<command> [world]
    aliases: [eworld]
  worth:
    description: Calculates the worth of items in hand or as specified.
    usage: /<command> <<itemname>|<id>|hand|inventory|blocks> [-][amount]
    aliases: [eprice,price,eworth]

permissions:
  essentials.*:
    default: op
    description: Give players with op everything by default
    children:
      essentials.gamemode.*: true
  # These permissions can't be assigned from player-commands for compatibility reasons
  essentials.teleport.cooldown.bypass.tpa:
    default: true
    description: If the player does not have this permission, /tpa will have cooldown even with the parent bypass perm
  essentials.teleport.cooldown.bypass.back:
    default: true
    description: If the player does not have this permission, /back will have cooldown even with the parent bypass perm
  essentials.gamemode.*:
    default: op
    children:
      essentials.gamemode: true
      essentials.gamemode.others: true
      essentials.gamemode.all: true
