# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: EssentialsAntiBuild
main: com.earth2me.essentials.antibuild.EssentialsAntiBuild
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://essentialsx.net/
description: Provides build protection.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, Iaccidentally]
depend: [Essentials]
api-version: "1.13"

permissions:
  essentials.exempt.protect:
    default: false
    description: Exempt from EssentialsProtect/EssentialsAntiBuild protections
    children:
      essentials.protect.alerts.notrigger: true
      essentials.protect.exemptbreak: true
      essentials.protect.exemptplacement: true
      essentials.protect.exemptusage: true
