# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: EssentialsGeoIP
main: com.earth2me.essentials.geoip.EssentialsGeoIP
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://essentialsx.net/
description: Shows the country or city of a user on login and /whois.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, kjiang, pop4959]
depend: [Essentials]
api-version: 1.13
folia-supported: true
