name: EssentialsDiscordLink
main: net.essentialsx.discordlink.EssentialsDiscordLink
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://essentialsx.net/
description: EssentialsX Discord addon which allows you link your Minecraft and Discord accounts together.
authors: [JRoy]
depend: [EssentialsDiscord]
api-version: 1.13
folia-supported: true
commands:
  link:
    description: Generates a code to link your Minecraft account to Discord.
    usage: /<command>
    aliases: [elink, discordlink, ediscordlink]
  unlink:
    description: Unlinks your Minecraft account from any associated Discord account.
    usage: /<command>
    aliases: [eunlink, discordunlink, ediscordunlink]
