name: Report a bug
about: Report a bug in EssentialsX.
labels: 'bug: unconfirmed'
inputs:
- type: description
  attributes:
    value: |
      Thanks for taking the time to report an EssentialsX bug! Fill out the form below to provide us with info to help fix the bug.
      Only use this if you're 100% sure you've found a bug and can reproduce it. If you're looking for general help with EssentialsX, try the Q&A forum or MOSS Discord server.
- type: multi_select
  attributes:
    label: Type of bug
    description: What type of bug is this? Choose all that apply.
    required: true
    choices:
      - Performance issue or memory leak
      - Data loss
      - Exploit
      - Compatibility issue
      - Error in console
      - Other unexpected behaviour

- type: textarea
  attributes:
    label: "`/ess version` output"
    description: Run `/ess version` in the console, then copy and paste the full output of the command into this box.
    required: true
- type: input
  attributes:
    label: Server startup log
    description: Upload your server startup log (from the start of `latest.log` up to where it says "Done!") to either https://paste.gg or https://gist.github.com, save and then paste the link in this box.
    required: true
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"
- type: input
  attributes:
    label: EssentialsX config files
    description: Upload your EssentialsX `config.yml` (and any other relevant files like `kits.yml`) to either https://paste.gg or https://gist.github.com, save and then paste the link in this box. If you included those files in the same paste as your startup log, paste the same link here.
    required: true
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"
- type: input
  attributes:
    label: Error log (if applicable)
    description: If you are reporting a console error, upload any relevant log excerpts to either https://paste.gg or https://gist.github.com, save and the paste the link in this box. If you included those files in the same paste as your startup log, paste the same link here.
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"

- type: textarea
  attributes:
    label: Bug description
    description: Describe roughly what the bug is here.
    required: true
    placeholder: |
      Example: "When running /nuke after putting everyone into adventure mode, there aren't any explosions..."
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Provide an example of how to trigger the bug.
    required: true
    placeholder: |
      Example:
      1. Have at least 3 people online
      2. Run `/gma *` to put everyone into adventure mode
      3. Run `/nuke`
- type: textarea
  attributes:
    label: Expected behaviour
    description: Explain what you should expect to happen.
    required: true
    placeholder: |
      Example: "Everything should explode!"
- type: textarea
  attributes:
    label: Actual behaviour
    description: Explain what actually happens.
    required: true
    placeholder: |
      Example: "Everything doesn't explode :("

- type: description
  attributes:
    value: |
      In the text box below, you can attach any relevant screenshots, files and links to Timings/spark profiler reports. You can also include a link to a heapdump if necessary, but please make sure you don't include any private player data in the heapdump.

