# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: EssentialsUpdate
main: com.earth2me.essentials.update.EssentialsUpdate
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: TeamCity
description: This plugin allows to install or update all Essentials plugins
authors: [snowleo]
commands:
  essentialsupdate:
    description: Install or update the Essentials plugins.
    usage: /<command>
  essentialshelp:
    description: Get help from the Essentials support chat.
    usage: /<command>
permissions:
  essentials.update:
    description: Allows you to update Essentials
    default: op
  essentials.helpchat:
    description: Allows you to join Essentials help chat
    default: op