# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: EssentialsChat
main: com.earth2me.essentials.chat.EssentialsChat
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://essentialsx.net/
description: Provides chat control features for Essentials.  Requires Permissions.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally]
depend: [Essentials]
api-version: 1.13
commands:
  toggleshout:
    description: Toggles whether you are talking in shout mode
    usage: /<command> [player] [on|off]
    aliases: [etoggleshout]
