# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: EssentialsXMPP
main: com.earth2me.essentials.xmpp.EssentialsXMPP
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: http://ess.khhq.net/wiki/XMPP
description: Provides XMPP communication.
authors: [snowleo]
depend: [Essentials]
api-version: 1.13
commands:
  setxmpp:
    description: Sets your XMPP address.
    usage: /<command> <address>
  xmpp:
    description: Sends a message to a player.
    usage: /<command> <player> <message>
  xmppspy:
    description: Toggles XMPP spy for all messages.
    usage: /<command> <player>
