# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: EssentialsSpawn
main: com.earth2me.essentials.spawn.EssentialsSpawn
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: http://tiny.cc/EssentialsCommands
description: Provides spawn control commands, utilizing Essentials.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits]
depend: [Essentials]
api-version: 1.13
commands:
  setspawn:
    description: Sets the spawn point to your current position.
    permission: essentials.setspawn
    usage: /<command> <group>
    aliases: [esetspawn]
  spawn:
    description: Teleports to the spawn point.
    permission: essentials.spawn
    usage: /<command> [player]
    aliases: [espawn]
permissions:
  essentials.spawn-on-join.exempt:
    default: false
    description: "Bypass spawn teleportation on join when spawn-on-join is true."
