name: Build Pull Request

on:
  push:
    branches:
    - mc/* # MC version updates
    - pr/* # PR rebases
  pull_request:
    branches:
    - 2.x
    - mc/*
    - dev/*

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build --stacktrace

    - name: Publish JUnit report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() # Run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test*/TEST-*.xml'

    - name: Archive plugin jars on GitHub
      uses: actions/upload-artifact@v4
      with:
        name: EssentialsX plugin jars
        path: jars/
